### ISSUE TITLE
NameError: name 'GL_FOG' is not defined

### ISSUE THREAD

**Issue by MasterHansCoding** [fogleman/Minecraft#147]
When I run main.py I get this error. What should I do?

**Comment by captain-wangrun-cn** [comment]
me too

**Comment by ghost** [comment]
me too

**Comment by Dada010101** [comment]
me too...

**Comment by rish-hyun** [comment]
I got the same error,
I resolved by installing PyOpenGL
```
pip install PyOpenGL
```

And later imported these two statements
```
from OpenGL.GL import *
from OpenGL.GLU import *
```

Import and NameError are resolved but now I'm getting another error
```
raise GLException('(0x%x): %s' % (error, msg))
pyglet.gl.lib.GLException: (0x500): Invalid enum. An unacceptable value is specified for an enumerated argument.
```

**Comment by rish-hyun** [comment]
I got the same error,
I resolved by installing PyOpenGL
```
pip install PyOpenGL
```

And later imported these two statements
```
from OpenGL.GL import *
from OpenGL.GLU import *
```

Import and NameError are resolved but now I'm getting another error
```
raise GLException('(0x%x): %s' % (error, msg))
pyglet.gl.lib.GLException: (0x500): Invalid enum. An unacceptable value is specified for an enumerated argument.
```

**Comment by rish-hyun** [comment]
> 

I've downgraded to `pyglet==1.5.27`, and it's working!

**Comment by rish-hyun** [comment]
> I got the same error, I resolved by installing PyOpenGL
> 
> ```
> pip install PyOpenGL
> ```
> 
> And later imported these two statements
> 
> ```
> from OpenGL.GL import *
> from OpenGL.GLU import *
> ```
> 
> Import and NameError are resolved but now I'm getting another error
> 
> ```
> raise GLException('(0x%x): %s' % (error, msg))
> pyglet.gl.lib.GLException: (0x500): Invalid enum. An unacceptable value is specified for an enumerated argument.
> ```

I've downgraded to `pyglet==1.5.27`, and it's working! No need to install PyOpenGL

**Comment by michaelboerman** [comment]
> > I got the same error, I resolved by installing PyOpenGL
> > ```
> > pip install PyOpenGL
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And later imported these two statements
> > ```
> > from OpenGL.GL import *
> > from OpenGL.GLU import *
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Import and NameError are resolved but now I'm getting another error
> > ```
> > raise GLException('(0x%x): %s' % (error, msg))
> > pyglet.gl.lib.GLException: (0x500): Invalid enum. An unacceptable value is specified for an enumerated argument.
> > ```
> 
> I've downgraded to `pyglet==1.5.27`, and it's working! No need to install PyOpenGL

Thank you for posting your solution! Your steps worked for me.

For others downgrading pyglet, you can do so by running `pip install pyglet==1.5.27`

**Comment by iTSiolinux** [comment]
i guess git pull the pyglet version in the how to run in the README.md add ' pip install pyglet==1.5.27 '

**Comment by Sjxooooooooooooooooooooooooooo** [comment]
Me too.
I move it to my new laptop,but it got this error…
What can I do?
![Uploading QQ截图20231216204103.png…]()

**Comment by Sjxooooooooooooooooooooooooooo** [comment]
Me too.
I move it to my new laptop,but it got this error…
What can I do?
`[Running] python -u "e:\Minecraft-master\main.py"
Traceback (most recent call last):
  File "e:\Minecraft-master\main.py", line 902, in <module>
    main()
  File "e:\Minecraft-master\main.py", line 897, in main
    setup()
  File "e:\Minecraft-master\main.py", line 890, in setup
    setup_fog()
  File "e:\Minecraft-master\main.py", line 861, in setup_fog
    glEnable(GL_FOG)
             ^^^^^^
NameError: name 'GL_FOG' is not defined

[Done] exited with code=1 in 0.776 seconds
`

**Comment by superbread0158** [comment]
Me too.
 I move it to my new laptop,but it got this error…
 What can I do?
```
[Running] python -u "e:\Minecraft-master\main.py"
Traceback (most recent call last):
  File "e:\Minecraft-master\main.py", line 902, in <module>
    main()
  File "e:\Minecraft-master\main.py", line 897, in main
    setup()
  File "e:\Minecraft-master\main.py", line 890, in setup
    setup_fog()
  File "e:\Minecraft-master\main.py", line 861, in setup_fog
    glEnable(GL_FOG)
             ^^^^^^
NameError: name 'GL_FOG' is not defined

[Done] exited with code=1 in 0.776 seconds

```

**Comment by RequiemxOP** [comment]
![Screenshot 2024-04-08 120628](https://github.com/fogleman/Minecraft/assets/98585765/098f34fb-3c35-4598-a532-71dc687fa382)
