### ISSUE TITLE
pyglet.gl.lib.GLException: (0x500): Invalid enum. An unacceptable value is specified for an enumerated argument.

### ISSUE THREAD

**Issue by rish-hyun** [fogleman/Minecraft#148]
I'm getting an error
```
Traceback (most recent call last):
  File "c:\Users\risha\OneDrive\Documents\Python\pyglet-test\main.py", line 905, in <module>
    main()
  File "c:\Users\risha\OneDrive\Documents\Python\pyglet-test\main.py", line 900, in main
    setup()
  File "c:\Users\risha\OneDrive\Documents\Python\pyglet-test\main.py", line 893, in setup
    setup_fog()
  File "c:\Users\risha\OneDrive\Documents\Python\pyglet-test\main.py", line 864, in setup_fog
    glEnable(GL_FOG)
  File "C:\Users\risha\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyglet\gl\lib.py", line 114, in errcheck
    raise GLException('(0x%x): %s' % (error, msg))
pyglet.gl.lib.GLException: (0x500): Invalid enum. An unacceptable value is specified for an enumerated argument.
```

**Comment by Python-Sargent** [comment]
Something is wrong internally with the pyglet fog mechanics, this is usually caused by something passing in a variable that isn't what was expected.

Did you change any code?
You could also try turning fog off.
