### ISSUE TITLE
error

### ISSUE THREAD

**Issue by JaydenChao101** [fogleman/Minecraft#151]
Traceback (most recent call last):
  File "/media/jayden/My Passport/pygame/Minecraft/main.py", line 902, in <module>
    main()
  File "/media/jayden/My Passport/pygame/Minecraft/main.py", line 897, in main
    setup()
  File "/media/jayden/My Passport/pygame/Minecraft/main.py", line 890, in setup
    setup_fog()
  File "/media/jayden/My Passport/pygame/Minecraft/main.py", line 861, in setup_fog
    glEnable(GL_FOG)
NameError: name 'GL_FOG' is not defined

**Comment by michaelboerman** [comment]
Solution provided in #147; please try it and close this issue.

**Comment by Python-Sargent** [comment]
[RESOLVED ISSUE]

I got the same thing.

Traceback (most recent call last):
  File "C:\Users\Samuel\Documents\GitHub\Minecraft\main.py", line 902, in <module>
    main()
  File "C:\Users\Samuel\Documents\GitHub\Minecraft\main.py", line 897, in main
    setup()
  File "C:\Users\Samuel\Documents\GitHub\Minecraft\main.py", line 890, in setup
    setup_fog()
  File "C:\Users\Samuel\Documents\GitHub\Minecraft\main.py", line 861, in setup_fog
    glEnable(GL_FOG)
NameError: name 'GL_FOG' is not defined

must've gotten the wrong pyglet version.

trying to get the specified version gives:

  ERROR: HTTP error 404 while getting https://pyglet.googlecode.com/files/pyglet-1.2alpha1.tar.gz
ERROR: Could not install requirement https://pyglet.googlecode.com/files/pyglet-1.2alpha1.tar.gz because of HTTP error 404 Client Error: Not Found for url: https://pyglet.googlecode.com/files/pyglet-1.2alpha1.tar.gz for URL https://pyglet.googlecode.com/files/pyglet-1.2alpha1.tar.gz

there are two other ways to do this, mentioned in #147 both work.

**Comment by Python-Sargent** [comment]
#147
