### ISSUE TITLE
NameError: name 'GL_FOG' is not defined

### ISSUE THREAD

**Issue by 4nkanpaa** [fogleman/Minecraft#159]

**Comment by HarshuboiPlayz** [comment]
im getting the same error

**Comment by uuk0** [comment]
This is caused by the wrong pyglet version; you need pyglet < 2.0, at the moment the latst version < 2.0 is 1.5.29

Pyglet 2.0 was a breaking change, changing to a more modern OpenGL version, which was also breaking, so the whole rendering stuff is not working with pyglet 2.0, including the fog.

**Comment by SherrySoft** [comment]
> This is caused by the wrong pyglet version; you need pyglet < 2.0, at the moment the latst version < 2.0 is 1.5.29
> 
> Pyglet 2.0 was a breaking change, changing to a more modern OpenGL version, which was also breaking, so the whole rendering stuff is not working with pyglet 2.0, including the fog.

how to install then?

**Comment by uuk0** [comment]
If you used pip, first uninstall: "\<python command\> -m pip uninstall pyglet", and than reinstall the version you want by "\<python command\> -m pip install pyglet==1.5.29"

**Comment by Yjc135** [comment]
> 如果你用的是 pip，首先卸载：“<python command> -m pip uninstall pyglet”，然后通过“<python command> -m pip install pyglet==1.5.29”重新安装你想要的版本

怎么查看pyglet版本？

**Comment by MAHTMATCIS** [comment]
Why did this issue occur after I downgraded pyglet to 1.5.29

```
Traceback (most recent call last):
  File "*\Minecraft_pyglet\main.py", line 10, in <module>
    from pyglet.gl import *
  File "*\Python314\Lib\site-packages\pyglet\gl\__init__.py", line 219, in <module>
    from .win32 import Win32Config as Config
  File "*\Python314\Lib\site-packages\pyglet\gl\win32.py", line 36, in <module>
    from pyglet.canvas.win32 import Win32Canvas
  File "*\Python314\Lib\site-packages\pyglet\canvas\__init__.py", line 110, in <module>
    from pyglet.canvas.win32 import Win32Display as Display
  File "*\Python314\Lib\site-packages\pyglet\canvas\win32.py", line 3, in <module>
    from pyglet.libs.win32 import _user32
  File "*\Python314\Lib\site-packages\pyglet\libs\win32\__init__.py", line 41, in <module>
    from . import com
  File "*\Python314\Lib\site-packages\pyglet\libs\win32\com.py", line 240, in <module>
    class COMPointer(ctypes.c_void_p, metaclass=COMPointerMeta):
    ...<18 lines>...
                    raise TypeError("Interface {} doesn't have a pointer in this class.".format(cls.__name__))
  File "*\Python314\Lib\site-packages\pyglet\libs\win32\com.py", line 214, in __new__
    _pointer_type_cache[cls] = type(COMPointer)("POINTER({})".format(cls.__name__),
                                    ^^^^^^^^^^
NameError: name 'COMPointer' is not defined. Did you mean: 'COMPointerMeta'?
```
