### ISSUE TITLE
Failed to create drawable

### ISSUE THREAD

**Issue by bert** [fogleman/Minecraft#40]
Hi,

Minecraft won't start and gives the following blurb:

[bert@draaikolk Minecraft]$ python main.py
failed to create drawable
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from pyglet.gl import *
  File "/usr/lib/python2.6/site-packages/pyglet/gl/**init**.py", line 510, in <module>
    import pyglet.window
  File "/usr/lib/python2.6/site-packages/pyglet/window/**init**.py", line 1684, in <module>
    gl._create_shadow_window()
  File "/usr/lib/python2.6/site-packages/pyglet/gl/__init__.py", line 494, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/usr/lib/python2.6/site-packages/pyglet/window/xlib/__init__.py", line 474, in **init**
    super(XlibWindow, self).**init**(_args, *_kwargs)
  File "/usr/lib/python2.6/site-packages/pyglet/window/**init**.py", line 686, in **init**
    self._create()
  File "/usr/lib/python2.6/site-packages/pyglet/window/xlib/__init__.py", line 683, in _create
    self.switch_to()
  File "/usr/lib/python2.6/site-packages/pyglet/window/xlib/__init__.py", line 781, in switch_to
    self._context.set_current()
  File "/usr/lib/python2.6/site-packages/pyglet/gl/__init__.py", line 345, in set_current
    self._info.set_active_context()
  File "/usr/lib/python2.6/site-packages/pyglet/gl/gl_info.py", line 91, in set_active_context
    self.vendor = cast(glGetString(GL_VENDOR), c_char_p).value
  File "/usr/lib/python2.6/site-packages/pyglet/gl/lib.py", line 105, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: invalid value

Running on Fedora 13 with:
python-2.6.4-27.fc13.i686
python-pip-0.8-1.fc13.noarch
pyglet-1.1.4-1.fc13.noarch

**Comment by Aareon** [comment]
@bert, this repository’s minimum Python requirement is `python2.7`. Older versions are not guaranteed to work.
