### ISSUE TITLE
Library "GLU" not found

### ISSUE THREAD

**Issue by helxsz** [fogleman/Minecraft#46]
I have installed pyglet, when running the main.py, a error came up saying 

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from pyglet.gl import *
  File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/**init**.py", line 99, in <module>
    from pyglet.gl.lib import GLException
  File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/lib.py", line 143, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/lib_glx.py", line 49, in <module>
    glu_lib = pyglet.lib.load_library('GLU')
  File "/usr/local/lib/python2.7/dist-packages/pyglet/lib.py", line 122, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "GLU" not found.

But I can't use pip to install the GLU library,  where is the GLU library ?

**Comment by Aareon** [comment]
First, try; `sudo apt-get install freeglut3-dev`

If that doesn’t work, try manually searching for the library; `sudo apt-cache search glut`

**Comment by johnbhlm** [comment]
@Aareon After apt-cache search glut ,what to do next?

**Comment by Aareon** [comment]
@johnbhlm Sorry for the very late reply, better late than never ig.
What was the output of `apt-cache search glut`?

If anyone else is struggling with this issue, please try installing `mesa` and/or `mesa-utils` for whichever distribution of Linux you're using. It's a google search away. When I originally answered in this thread, I was referencing [this StackOverflow answer](https://askubuntu.com/a/937531).

**Comment by raufie** [comment]
`sudo apt-get install freeglut3-dev` solves the problem in ubuntu 20.04 wsl2 win 10
I actually had the problem installing open AI gym, but found a solution here XD
