### ISSUE TITLE
Not working on python 3.4 and pyglet development

### ISSUE THREAD

**Issue by Flowkap** [fogleman/Minecraft#49]
Failing with:

```
Traceback (most recent call last):
  File "main.py", line 894, in <module>
    main()
  File "main.py", line 886, in main
    window = Window(width=800, height=600, caption='Pyglet', resizable=True)
  File "main.py", line 480, in __init__
    self.model = Model()
  File "main.py", line 150, in __init__
    self._initialize()
  File "main.py", line 159, in _initialize
    for x in xrange(-n, n + 1, s):
NameError: name 'xrange' is not defined
```

**Comment by Aareon** [comment]
@fogleman, solved 3 years ago. Can close.
