### ISSUE TITLE
ImportError: No module named 'future' -Python 3.5

### ISSUE THREAD

**Issue by mfonner** [fogleman/Minecraft#65]
Error cut and pasted: 

    Failed to get python-future
    Traceback (most recent call last):
      File "C:\Python3.5\lib\site-packages\pyglet\__init__.py", line 44, in <module>
        import future
    ImportError: No module named 'future'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\mfonner12\Downloads\Minecraft-master\main.py", line 6, in <module>
        from pyglet import image
      File "C:\Python3.5\lib\site-packages\pyglet\__init__.py", line 56, in <module>
        import future
    ImportError: No module named 'future'`

**Comment by ProgVal** [comment]
This bug should be failed against pyglet.

**Comment by ProgVal** [comment]
This bug should be filed against pyglet.

**Comment by mfonner** [comment]
Will do, thanks!

**Comment by ProgVal** [comment]
Hmm, actually, I don't know where the `Failed to get python-future` comes from

**Comment by ProgVal** [comment]
Have you tried `pip install python-future`?

**Comment by mfonner** [comment]
I'm running that now and will let you know.

**Comment by mfonner** [comment]
Installed Future and now there is an error with xrange:

    Traceback (most recent call last):
      File "C:\Users\mfonner12\Downloads\Minecraft-master\main.py", line 894, in <module>
        main()
      File "C:\Users\mfonner12\Downloads\Minecraft-master\main.py", line 886, in main
        window = Window(width=800, height=600, caption='Pyglet', resizable=True)
      File "C:\Users\mfonner12\Downloads\Minecraft-master\main.py", line 480, in __init__
        self.model = Model()
      File "C:\Users\mfonner12\Downloads\Minecraft-master\main.py", line 150, in __init__
        self._initialize()
      File "C:\Users\mfonner12\Downloads\Minecraft-master\main.py", line 159, in _initialize
        for x in xrange(-n, n + 1, s):
    NameError: name 'xrange' is not defined

**Comment by ProgVal** [comment]
I wrote these fixes awhile ago for Python 3, you can try them: https://github.com/fogleman/Minecraft/compare/master...ProgVal:python3

**Comment by mfonner** [comment]
Perfect! Thank you.
