### ISSUE TITLE
Can not run main.py

### ISSUE THREAD

**Issue by thinhduckhoi** [fogleman/Minecraft#69]
As i followed the steps, i got stuck when running the main.py
[root@ip-10-0-7-118 Minecraft]# python main.py
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from pyglet.gl import *
  File "/usr/lib/python2.7/site-packages/pyglet/gl/__init__.py", line 97, in <module>
    from pyglet.gl.lib import GLException
  File "/usr/lib/python2.7/site-packages/pyglet/gl/lib.py", line 142, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/usr/lib/python2.7/site-packages/pyglet/gl/lib_glx.py", line 50, in <module>
    gl_lib = pyglet.lib.load_library('GL')
  File "/usr/lib/python2.7/site-packages/pyglet/lib.py", line 160, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "GL" not found.
Can you tell me how to fix it please?
I'm running python 2.7.5 on Centos 7.2

**Comment by ProgVal** [comment]
Try this: http://stackoverflow.com/a/7941950/539465

**Comment by thinhduckhoi** [comment]
Ah sorry i think i just forgot.
I don't have OS graphic version, now i'm running CentOS7 on Instance EC2 on AWS. That's totally command-line interface.

**Comment by ProgVal** [comment]
You need an X server to run this.
